// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Historical PnL snapshots for analytics and performance tracking
type PnlHistory struct {
	ID       int64 `json:"id"`
	WalletID int64 `json:"wallet_id"`
	// Time period: daily, weekly, monthly
	PeriodType  string             `json:"period_type"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	TotalPnlUsd pgtype.Numeric     `json:"total_pnl_usd"`
	// PnL from completed trades
	RealizedPnlUsd pgtype.Numeric `json:"realized_pnl_usd"`
	// PnL from open positions
	UnrealizedPnlUsd       pgtype.Numeric `json:"unrealized_pnl_usd"`
	TotalPortfolioValueUsd pgtype.Numeric `json:"total_portfolio_value_usd"`
	SolBalance             pgtype.Numeric `json:"sol_balance"`
	ActivePositionsCount   int32          `json:"active_positions_count"`
	TradesCount            int32          `json:"trades_count"`
	// Number of profitable trades in period
	WinningTrades int32 `json:"winning_trades"`
	// Number of loss-making trades in period
	LosingTrades int32              `json:"losing_trades"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Active and historical token positions for portfolio tracking
type TokenPositions struct {
	ID           int64          `json:"id"`
	WalletID     int64          `json:"wallet_id"`
	TokenAddress string         `json:"token_address"`
	TokenSymbol  pgtype.Text    `json:"token_symbol"`
	Amount       pgtype.Numeric `json:"amount"`
	EntryPrice   pgtype.Numeric `json:"entry_price"`
	CurrentPrice pgtype.Numeric `json:"current_price"`
	// Calculated PnL in USD, updated periodically
	PnlUsd    pgtype.Numeric     `json:"pnl_usd"`
	OpenedAt  pgtype.Timestamptz `json:"opened_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// FALSE when position is closed/sold
	IsActive bool `json:"is_active"`
}

// Cached SOL balances for user wallets with TTL mechanism
type UserBalances struct {
	ID          int64              `json:"id"`
	WalletID    int64              `json:"wallet_id"`
	SolBalance  pgtype.Numeric     `json:"sol_balance"`
	LastUpdated pgtype.Timestamptz `json:"last_updated"`
	// TTL for balance cache, typically 5-10 minutes
	CacheValidUntil pgtype.Timestamptz `json:"cache_valid_until"`
}

// Per-user trading preferences and defaults
type UserSettings struct {
	UserID int64 `json:"user_id"`
	// Buy slippage tolerance in percentage (1.0-90.0)
	BuySlippage pgtype.Numeric `json:"buy_slippage"`
	// Sell slippage tolerance in percentage (1.0-90.0)
	SellSlippage pgtype.Numeric `json:"sell_slippage"`
	// Priority fee in lamports for transactions
	PriorityFee int64 `json:"priority_fee"`
	// Jito bundle tip in lamports
	JitoTip int64 `json:"jito_tip"`
	// Default SOL amount for token purchases
	DefaultSolAmount pgtype.Numeric     `json:"default_sol_amount"`
	SellPreset25     pgtype.Numeric     `json:"sell_preset_25"`
	SellPreset50     pgtype.Numeric     `json:"sell_preset_50"`
	SellPreset75     pgtype.Numeric     `json:"sell_preset_75"`
	SellPreset100    pgtype.Numeric     `json:"sell_preset_100"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	// Customizable buy preset 1 in SOL (0.001-100)
	BuyPreset1 pgtype.Numeric `json:"buy_preset_1"`
	// Customizable buy preset 2 in SOL (0.001-100)
	BuyPreset2 pgtype.Numeric `json:"buy_preset_2"`
	// Customizable buy preset 3 in SOL (0.001-100)
	BuyPreset3 pgtype.Numeric `json:"buy_preset_3"`
	// Customizable buy preset 4 in SOL (0.001-100)
	BuyPreset4 pgtype.Numeric `json:"buy_preset_4"`
	// Customizable buy preset 5 in SOL (0.001-100)
	BuyPreset5 pgtype.Numeric `json:"buy_preset_5"`
}

type Wallet struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	Mnemonic   pgtype.Text        `json:"mnemonic"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	IsDefault  bool               `json:"is_default"`
	// AES-256-GCM encrypted private key
	EncryptedPrivateKey []byte `json:"encrypted_private_key"`
	// Nonce for private key encryption
	PrivateKeyNonce []byte `json:"private_key_nonce"`
	// AES-256-GCM encrypted mnemonic phrase
	EncryptedMnemonic []byte `json:"encrypted_mnemonic"`
	// Nonce for mnemonic encryption
	MnemonicNonce []byte `json:"mnemonic_nonce"`
	// Version of encryption scheme used
	EncryptionVersion int32 `json:"encryption_version"`
	// Timestamp when encryption was applied
	EncryptedAt pgtype.Timestamptz `json:"encrypted_at"`
}
