// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pnl_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPnLRecord = `-- name: CreatePnLRecord :exec
INSERT INTO pnl_history (wallet_id, period_type, period_start, period_end, total_pnl_usd, realized_pnl_usd, 
                        unrealized_pnl_usd, total_portfolio_value_usd, sol_balance, active_positions_count,
                        trades_count, winning_trades, losing_trades, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW())
`

type CreatePnLRecordParams struct {
	WalletID               int64              `json:"wallet_id"`
	PeriodType             string             `json:"period_type"`
	PeriodStart            pgtype.Timestamptz `json:"period_start"`
	PeriodEnd              pgtype.Timestamptz `json:"period_end"`
	TotalPnlUsd            pgtype.Numeric     `json:"total_pnl_usd"`
	RealizedPnlUsd         pgtype.Numeric     `json:"realized_pnl_usd"`
	UnrealizedPnlUsd       pgtype.Numeric     `json:"unrealized_pnl_usd"`
	TotalPortfolioValueUsd pgtype.Numeric     `json:"total_portfolio_value_usd"`
	SolBalance             pgtype.Numeric     `json:"sol_balance"`
	ActivePositionsCount   int32              `json:"active_positions_count"`
	TradesCount            int32              `json:"trades_count"`
	WinningTrades          int32              `json:"winning_trades"`
	LosingTrades           int32              `json:"losing_trades"`
}

func (q *Queries) CreatePnLRecord(ctx context.Context, arg CreatePnLRecordParams) error {
	_, err := q.db.Exec(ctx, createPnLRecord,
		arg.WalletID,
		arg.PeriodType,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TotalPnlUsd,
		arg.RealizedPnlUsd,
		arg.UnrealizedPnlUsd,
		arg.TotalPortfolioValueUsd,
		arg.SolBalance,
		arg.ActivePositionsCount,
		arg.TradesCount,
		arg.WinningTrades,
		arg.LosingTrades,
	)
	return err
}

const deleteOldPnLRecords = `-- name: DeleteOldPnLRecords :exec
DELETE FROM pnl_history
WHERE wallet_id = $1 AND period_start < $2
`

type DeleteOldPnLRecordsParams struct {
	WalletID    int64              `json:"wallet_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
}

func (q *Queries) DeleteOldPnLRecords(ctx context.Context, arg DeleteOldPnLRecordsParams) error {
	_, err := q.db.Exec(ctx, deleteOldPnLRecords, arg.WalletID, arg.PeriodStart)
	return err
}

const getAllWalletsPnLForPeriod = `-- name: GetAllWalletsPnLForPeriod :many
SELECT ph.id, ph.wallet_id, ph.period_type, ph.period_start, ph.period_end, ph.total_pnl_usd, ph.realized_pnl_usd, 
       ph.unrealized_pnl_usd, ph.total_portfolio_value_usd, ph.sol_balance, ph.active_positions_count,
       ph.trades_count, ph.winning_trades, ph.losing_trades, ph.created_at,
       w.user_id, w.name as wallet_name
FROM pnl_history ph
JOIN wallet w ON ph.wallet_id = w.id
WHERE ph.period_type = $1 AND ph.period_start = $2
ORDER BY ph.total_pnl_usd DESC
`

type GetAllWalletsPnLForPeriodParams struct {
	PeriodType  string             `json:"period_type"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
}

type GetAllWalletsPnLForPeriodRow struct {
	ID                     int64              `json:"id"`
	WalletID               int64              `json:"wallet_id"`
	PeriodType             string             `json:"period_type"`
	PeriodStart            pgtype.Timestamptz `json:"period_start"`
	PeriodEnd              pgtype.Timestamptz `json:"period_end"`
	TotalPnlUsd            pgtype.Numeric     `json:"total_pnl_usd"`
	RealizedPnlUsd         pgtype.Numeric     `json:"realized_pnl_usd"`
	UnrealizedPnlUsd       pgtype.Numeric     `json:"unrealized_pnl_usd"`
	TotalPortfolioValueUsd pgtype.Numeric     `json:"total_portfolio_value_usd"`
	SolBalance             pgtype.Numeric     `json:"sol_balance"`
	ActivePositionsCount   int32              `json:"active_positions_count"`
	TradesCount            int32              `json:"trades_count"`
	WinningTrades          int32              `json:"winning_trades"`
	LosingTrades           int32              `json:"losing_trades"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UserID                 int64              `json:"user_id"`
	WalletName             string             `json:"wallet_name"`
}

func (q *Queries) GetAllWalletsPnLForPeriod(ctx context.Context, arg GetAllWalletsPnLForPeriodParams) ([]GetAllWalletsPnLForPeriodRow, error) {
	rows, err := q.db.Query(ctx, getAllWalletsPnLForPeriod, arg.PeriodType, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllWalletsPnLForPeriodRow{}
	for rows.Next() {
		var i GetAllWalletsPnLForPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.PeriodType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalPnlUsd,
			&i.RealizedPnlUsd,
			&i.UnrealizedPnlUsd,
			&i.TotalPortfolioValueUsd,
			&i.SolBalance,
			&i.ActivePositionsCount,
			&i.TradesCount,
			&i.WinningTrades,
			&i.LosingTrades,
			&i.CreatedAt,
			&i.UserID,
			&i.WalletName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyPnL = `-- name: GetDailyPnL :many
SELECT id, wallet_id, period_type, period_start, period_end, total_pnl_usd, realized_pnl_usd, 
       unrealized_pnl_usd, total_portfolio_value_usd, sol_balance, active_positions_count,
       trades_count, winning_trades, losing_trades, created_at
FROM pnl_history
WHERE wallet_id = $1 AND period_type = 'daily'
ORDER BY period_start DESC
LIMIT $2
`

type GetDailyPnLParams struct {
	WalletID int64 `json:"wallet_id"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) GetDailyPnL(ctx context.Context, arg GetDailyPnLParams) ([]PnlHistory, error) {
	rows, err := q.db.Query(ctx, getDailyPnL, arg.WalletID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PnlHistory{}
	for rows.Next() {
		var i PnlHistory
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.PeriodType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalPnlUsd,
			&i.RealizedPnlUsd,
			&i.UnrealizedPnlUsd,
			&i.TotalPortfolioValueUsd,
			&i.SolBalance,
			&i.ActivePositionsCount,
			&i.TradesCount,
			&i.WinningTrades,
			&i.LosingTrades,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyPnL = `-- name: GetMonthlyPnL :many
SELECT id, wallet_id, period_type, period_start, period_end, total_pnl_usd, realized_pnl_usd, 
       unrealized_pnl_usd, total_portfolio_value_usd, sol_balance, active_positions_count,
       trades_count, winning_trades, losing_trades, created_at
FROM pnl_history
WHERE wallet_id = $1 AND period_type = 'monthly'
ORDER BY period_start DESC
LIMIT $2
`

type GetMonthlyPnLParams struct {
	WalletID int64 `json:"wallet_id"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) GetMonthlyPnL(ctx context.Context, arg GetMonthlyPnLParams) ([]PnlHistory, error) {
	rows, err := q.db.Query(ctx, getMonthlyPnL, arg.WalletID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PnlHistory{}
	for rows.Next() {
		var i PnlHistory
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.PeriodType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalPnlUsd,
			&i.RealizedPnlUsd,
			&i.UnrealizedPnlUsd,
			&i.TotalPortfolioValueUsd,
			&i.SolBalance,
			&i.ActivePositionsCount,
			&i.TradesCount,
			&i.WinningTrades,
			&i.LosingTrades,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPnLByPeriod = `-- name: GetPnLByPeriod :one
SELECT id, wallet_id, period_type, period_start, period_end, total_pnl_usd, realized_pnl_usd, 
       unrealized_pnl_usd, total_portfolio_value_usd, sol_balance, active_positions_count,
       trades_count, winning_trades, losing_trades, created_at
FROM pnl_history
WHERE wallet_id = $1 AND period_type = $2 AND period_start = $3
`

type GetPnLByPeriodParams struct {
	WalletID    int64              `json:"wallet_id"`
	PeriodType  string             `json:"period_type"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
}

func (q *Queries) GetPnLByPeriod(ctx context.Context, arg GetPnLByPeriodParams) (PnlHistory, error) {
	row := q.db.QueryRow(ctx, getPnLByPeriod, arg.WalletID, arg.PeriodType, arg.PeriodStart)
	var i PnlHistory
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.PeriodType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TotalPnlUsd,
		&i.RealizedPnlUsd,
		&i.UnrealizedPnlUsd,
		&i.TotalPortfolioValueUsd,
		&i.SolBalance,
		&i.ActivePositionsCount,
		&i.TradesCount,
		&i.WinningTrades,
		&i.LosingTrades,
		&i.CreatedAt,
	)
	return i, err
}

const getPnLHistory = `-- name: GetPnLHistory :many
SELECT id, wallet_id, period_type, period_start, period_end, total_pnl_usd, realized_pnl_usd, 
       unrealized_pnl_usd, total_portfolio_value_usd, sol_balance, active_positions_count,
       trades_count, winning_trades, losing_trades, created_at
FROM pnl_history
WHERE wallet_id = $1 AND period_type = $2
ORDER BY period_start DESC
LIMIT $3
`

type GetPnLHistoryParams struct {
	WalletID   int64  `json:"wallet_id"`
	PeriodType string `json:"period_type"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) GetPnLHistory(ctx context.Context, arg GetPnLHistoryParams) ([]PnlHistory, error) {
	rows, err := q.db.Query(ctx, getPnLHistory, arg.WalletID, arg.PeriodType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PnlHistory{}
	for rows.Next() {
		var i PnlHistory
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.PeriodType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalPnlUsd,
			&i.RealizedPnlUsd,
			&i.UnrealizedPnlUsd,
			&i.TotalPortfolioValueUsd,
			&i.SolBalance,
			&i.ActivePositionsCount,
			&i.TradesCount,
			&i.WinningTrades,
			&i.LosingTrades,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPnLSummaryStats = `-- name: GetPnLSummaryStats :one
SELECT 
    COUNT(*) as total_periods,
    SUM(total_pnl_usd) as cumulative_pnl_usd,
    AVG(total_pnl_usd) as avg_pnl_per_period,
    SUM(trades_count) as total_trades,
    SUM(winning_trades) as total_winning_trades,
    SUM(losing_trades) as total_losing_trades,
    MAX(total_pnl_usd) as best_period_pnl,
    MIN(total_pnl_usd) as worst_period_pnl,
    AVG(total_portfolio_value_usd) as avg_portfolio_value
FROM pnl_history
WHERE wallet_id = $1 AND period_type = $2
`

type GetPnLSummaryStatsParams struct {
	WalletID   int64  `json:"wallet_id"`
	PeriodType string `json:"period_type"`
}

type GetPnLSummaryStatsRow struct {
	TotalPeriods       int64       `json:"total_periods"`
	CumulativePnlUsd   int64       `json:"cumulative_pnl_usd"`
	AvgPnlPerPeriod    float64     `json:"avg_pnl_per_period"`
	TotalTrades        int64       `json:"total_trades"`
	TotalWinningTrades int64       `json:"total_winning_trades"`
	TotalLosingTrades  int64       `json:"total_losing_trades"`
	BestPeriodPnl      interface{} `json:"best_period_pnl"`
	WorstPeriodPnl     interface{} `json:"worst_period_pnl"`
	AvgPortfolioValue  float64     `json:"avg_portfolio_value"`
}

func (q *Queries) GetPnLSummaryStats(ctx context.Context, arg GetPnLSummaryStatsParams) (GetPnLSummaryStatsRow, error) {
	row := q.db.QueryRow(ctx, getPnLSummaryStats, arg.WalletID, arg.PeriodType)
	var i GetPnLSummaryStatsRow
	err := row.Scan(
		&i.TotalPeriods,
		&i.CumulativePnlUsd,
		&i.AvgPnlPerPeriod,
		&i.TotalTrades,
		&i.TotalWinningTrades,
		&i.TotalLosingTrades,
		&i.BestPeriodPnl,
		&i.WorstPeriodPnl,
		&i.AvgPortfolioValue,
	)
	return i, err
}

const getRecentPerformance = `-- name: GetRecentPerformance :many
SELECT id, wallet_id, period_type, period_start, period_end, total_pnl_usd, realized_pnl_usd, 
       unrealized_pnl_usd, total_portfolio_value_usd, sol_balance, active_positions_count,
       trades_count, winning_trades, losing_trades, created_at
FROM pnl_history
WHERE wallet_id = $1 AND period_start >= $2
ORDER BY period_start DESC
`

type GetRecentPerformanceParams struct {
	WalletID    int64              `json:"wallet_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
}

func (q *Queries) GetRecentPerformance(ctx context.Context, arg GetRecentPerformanceParams) ([]PnlHistory, error) {
	rows, err := q.db.Query(ctx, getRecentPerformance, arg.WalletID, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PnlHistory{}
	for rows.Next() {
		var i PnlHistory
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.PeriodType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalPnlUsd,
			&i.RealizedPnlUsd,
			&i.UnrealizedPnlUsd,
			&i.TotalPortfolioValueUsd,
			&i.SolBalance,
			&i.ActivePositionsCount,
			&i.TradesCount,
			&i.WinningTrades,
			&i.LosingTrades,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopPerformingPeriods = `-- name: GetTopPerformingPeriods :many
SELECT id, wallet_id, period_type, period_start, period_end, total_pnl_usd, realized_pnl_usd, 
       unrealized_pnl_usd, total_portfolio_value_usd, sol_balance, active_positions_count,
       trades_count, winning_trades, losing_trades, created_at
FROM pnl_history
WHERE wallet_id = $1 AND period_type = $2 AND total_pnl_usd > 0
ORDER BY total_pnl_usd DESC
LIMIT $3
`

type GetTopPerformingPeriodsParams struct {
	WalletID   int64  `json:"wallet_id"`
	PeriodType string `json:"period_type"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) GetTopPerformingPeriods(ctx context.Context, arg GetTopPerformingPeriodsParams) ([]PnlHistory, error) {
	rows, err := q.db.Query(ctx, getTopPerformingPeriods, arg.WalletID, arg.PeriodType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PnlHistory{}
	for rows.Next() {
		var i PnlHistory
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.PeriodType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalPnlUsd,
			&i.RealizedPnlUsd,
			&i.UnrealizedPnlUsd,
			&i.TotalPortfolioValueUsd,
			&i.SolBalance,
			&i.ActivePositionsCount,
			&i.TradesCount,
			&i.WinningTrades,
			&i.LosingTrades,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklyPnL = `-- name: GetWeeklyPnL :many
SELECT id, wallet_id, period_type, period_start, period_end, total_pnl_usd, realized_pnl_usd, 
       unrealized_pnl_usd, total_portfolio_value_usd, sol_balance, active_positions_count,
       trades_count, winning_trades, losing_trades, created_at
FROM pnl_history
WHERE wallet_id = $1 AND period_type = 'weekly'
ORDER BY period_start DESC
LIMIT $2
`

type GetWeeklyPnLParams struct {
	WalletID int64 `json:"wallet_id"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) GetWeeklyPnL(ctx context.Context, arg GetWeeklyPnLParams) ([]PnlHistory, error) {
	rows, err := q.db.Query(ctx, getWeeklyPnL, arg.WalletID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PnlHistory{}
	for rows.Next() {
		var i PnlHistory
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.PeriodType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalPnlUsd,
			&i.RealizedPnlUsd,
			&i.UnrealizedPnlUsd,
			&i.TotalPortfolioValueUsd,
			&i.SolBalance,
			&i.ActivePositionsCount,
			&i.TradesCount,
			&i.WinningTrades,
			&i.LosingTrades,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorstPerformingPeriods = `-- name: GetWorstPerformingPeriods :many
SELECT id, wallet_id, period_type, period_start, period_end, total_pnl_usd, realized_pnl_usd, 
       unrealized_pnl_usd, total_portfolio_value_usd, sol_balance, active_positions_count,
       trades_count, winning_trades, losing_trades, created_at
FROM pnl_history
WHERE wallet_id = $1 AND period_type = $2 AND total_pnl_usd < 0
ORDER BY total_pnl_usd ASC
LIMIT $3
`

type GetWorstPerformingPeriodsParams struct {
	WalletID   int64  `json:"wallet_id"`
	PeriodType string `json:"period_type"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) GetWorstPerformingPeriods(ctx context.Context, arg GetWorstPerformingPeriodsParams) ([]PnlHistory, error) {
	rows, err := q.db.Query(ctx, getWorstPerformingPeriods, arg.WalletID, arg.PeriodType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PnlHistory{}
	for rows.Next() {
		var i PnlHistory
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.PeriodType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TotalPnlUsd,
			&i.RealizedPnlUsd,
			&i.UnrealizedPnlUsd,
			&i.TotalPortfolioValueUsd,
			&i.SolBalance,
			&i.ActivePositionsCount,
			&i.TradesCount,
			&i.WinningTrades,
			&i.LosingTrades,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPnLRecord = `-- name: UpsertPnLRecord :exec
INSERT INTO pnl_history (wallet_id, period_type, period_start, period_end, total_pnl_usd, realized_pnl_usd, 
                        unrealized_pnl_usd, total_portfolio_value_usd, sol_balance, active_positions_count,
                        trades_count, winning_trades, losing_trades, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW())
ON CONFLICT (wallet_id, period_type, period_start)
DO UPDATE SET
    period_end = EXCLUDED.period_end,
    total_pnl_usd = EXCLUDED.total_pnl_usd,
    realized_pnl_usd = EXCLUDED.realized_pnl_usd,
    unrealized_pnl_usd = EXCLUDED.unrealized_pnl_usd,
    total_portfolio_value_usd = EXCLUDED.total_portfolio_value_usd,
    sol_balance = EXCLUDED.sol_balance,
    active_positions_count = EXCLUDED.active_positions_count,
    trades_count = EXCLUDED.trades_count,
    winning_trades = EXCLUDED.winning_trades,
    losing_trades = EXCLUDED.losing_trades,
    created_at = NOW()
`

type UpsertPnLRecordParams struct {
	WalletID               int64              `json:"wallet_id"`
	PeriodType             string             `json:"period_type"`
	PeriodStart            pgtype.Timestamptz `json:"period_start"`
	PeriodEnd              pgtype.Timestamptz `json:"period_end"`
	TotalPnlUsd            pgtype.Numeric     `json:"total_pnl_usd"`
	RealizedPnlUsd         pgtype.Numeric     `json:"realized_pnl_usd"`
	UnrealizedPnlUsd       pgtype.Numeric     `json:"unrealized_pnl_usd"`
	TotalPortfolioValueUsd pgtype.Numeric     `json:"total_portfolio_value_usd"`
	SolBalance             pgtype.Numeric     `json:"sol_balance"`
	ActivePositionsCount   int32              `json:"active_positions_count"`
	TradesCount            int32              `json:"trades_count"`
	WinningTrades          int32              `json:"winning_trades"`
	LosingTrades           int32              `json:"losing_trades"`
}

func (q *Queries) UpsertPnLRecord(ctx context.Context, arg UpsertPnLRecordParams) error {
	_, err := q.db.Exec(ctx, upsertPnLRecord,
		arg.WalletID,
		arg.PeriodType,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TotalPnlUsd,
		arg.RealizedPnlUsd,
		arg.UnrealizedPnlUsd,
		arg.TotalPortfolioValueUsd,
		arg.SolBalance,
		arg.ActivePositionsCount,
		arg.TradesCount,
		arg.WinningTrades,
		arg.LosingTrades,
	)
	return err
}
