// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: token_positions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdatePositionPrices = `-- name: BulkUpdatePositionPrices :exec
UPDATE token_positions
SET current_price = 
    CASE token_address
        WHEN $1 THEN $2
        WHEN $3 THEN $4
        WHEN $5 THEN $6
        ELSE current_price
    END,
    updated_at = NOW()
WHERE token_address IN ($1, $3, $5) AND is_active = true
`

type BulkUpdatePositionPricesParams struct {
	CurrentPrice   pgtype.Numeric `json:"current_price"`
	CurrentPrice_2 pgtype.Numeric `json:"current_price_2"`
	CurrentPrice_3 pgtype.Numeric `json:"current_price_3"`
	CurrentPrice_4 pgtype.Numeric `json:"current_price_4"`
	CurrentPrice_5 pgtype.Numeric `json:"current_price_5"`
	CurrentPrice_6 pgtype.Numeric `json:"current_price_6"`
}

func (q *Queries) BulkUpdatePositionPrices(ctx context.Context, arg BulkUpdatePositionPricesParams) error {
	_, err := q.db.Exec(ctx, bulkUpdatePositionPrices,
		arg.CurrentPrice,
		arg.CurrentPrice_2,
		arg.CurrentPrice_3,
		arg.CurrentPrice_4,
		arg.CurrentPrice_5,
		arg.CurrentPrice_6,
	)
	return err
}

const closeTokenPosition = `-- name: CloseTokenPosition :exec
UPDATE token_positions
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CloseTokenPosition(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, closeTokenPosition, id)
	return err
}

const createTokenPosition = `-- name: CreateTokenPosition :one
INSERT INTO token_positions (wallet_id, token_address, token_symbol, amount, entry_price, opened_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, wallet_id, token_address, token_symbol, amount, entry_price, current_price, pnl_usd, opened_at, updated_at, is_active
`

type CreateTokenPositionParams struct {
	WalletID     int64          `json:"wallet_id"`
	TokenAddress string         `json:"token_address"`
	TokenSymbol  pgtype.Text    `json:"token_symbol"`
	Amount       pgtype.Numeric `json:"amount"`
	EntryPrice   pgtype.Numeric `json:"entry_price"`
}

func (q *Queries) CreateTokenPosition(ctx context.Context, arg CreateTokenPositionParams) (TokenPositions, error) {
	row := q.db.QueryRow(ctx, createTokenPosition,
		arg.WalletID,
		arg.TokenAddress,
		arg.TokenSymbol,
		arg.Amount,
		arg.EntryPrice,
	)
	var i TokenPositions
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TokenAddress,
		&i.TokenSymbol,
		&i.Amount,
		&i.EntryPrice,
		&i.CurrentPrice,
		&i.PnlUsd,
		&i.OpenedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const deletePosition = `-- name: DeletePosition :exec
DELETE FROM token_positions
WHERE id = $1 AND wallet_id = $2
`

type DeletePositionParams struct {
	ID       int64 `json:"id"`
	WalletID int64 `json:"wallet_id"`
}

func (q *Queries) DeletePosition(ctx context.Context, arg DeletePositionParams) error {
	_, err := q.db.Exec(ctx, deletePosition, arg.ID, arg.WalletID)
	return err
}

const getActivePositionsByWallet = `-- name: GetActivePositionsByWallet :many
SELECT id, wallet_id, token_address, token_symbol, amount, entry_price, current_price, pnl_usd, opened_at, updated_at, is_active
FROM token_positions
WHERE wallet_id = $1 AND is_active = true
ORDER BY updated_at DESC
`

func (q *Queries) GetActivePositionsByWallet(ctx context.Context, walletID int64) ([]TokenPositions, error) {
	rows, err := q.db.Query(ctx, getActivePositionsByWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenPositions{}
	for rows.Next() {
		var i TokenPositions
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TokenAddress,
			&i.TokenSymbol,
			&i.Amount,
			&i.EntryPrice,
			&i.CurrentPrice,
			&i.PnlUsd,
			&i.OpenedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveTokenPosition = `-- name: GetActiveTokenPosition :one
SELECT id, wallet_id, token_address, token_symbol, amount, entry_price, current_price, pnl_usd, opened_at, updated_at, is_active
FROM token_positions
WHERE wallet_id = $1 AND token_address = $2 AND is_active = true
`

type GetActiveTokenPositionParams struct {
	WalletID     int64  `json:"wallet_id"`
	TokenAddress string `json:"token_address"`
}

func (q *Queries) GetActiveTokenPosition(ctx context.Context, arg GetActiveTokenPositionParams) (TokenPositions, error) {
	row := q.db.QueryRow(ctx, getActiveTokenPosition, arg.WalletID, arg.TokenAddress)
	var i TokenPositions
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TokenAddress,
		&i.TokenSymbol,
		&i.Amount,
		&i.EntryPrice,
		&i.CurrentPrice,
		&i.PnlUsd,
		&i.OpenedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getAllPositionsByWallet = `-- name: GetAllPositionsByWallet :many
SELECT id, wallet_id, token_address, token_symbol, amount, entry_price, current_price, pnl_usd, opened_at, updated_at, is_active
FROM token_positions
WHERE wallet_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetAllPositionsByWallet(ctx context.Context, walletID int64) ([]TokenPositions, error) {
	rows, err := q.db.Query(ctx, getAllPositionsByWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenPositions{}
	for rows.Next() {
		var i TokenPositions
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TokenAddress,
			&i.TokenSymbol,
			&i.Amount,
			&i.EntryPrice,
			&i.CurrentPrice,
			&i.PnlUsd,
			&i.OpenedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPositionsByToken = `-- name: GetPositionsByToken :many
SELECT tp.id, tp.wallet_id, tp.token_address, tp.token_symbol, tp.amount, tp.entry_price, tp.current_price, tp.pnl_usd, tp.opened_at, tp.updated_at, tp.is_active,
       w.user_id, w.name as wallet_name
FROM token_positions tp
JOIN wallet w ON tp.wallet_id = w.id
WHERE tp.token_address = $1 AND tp.is_active = $2
ORDER BY tp.updated_at DESC
`

type GetPositionsByTokenParams struct {
	TokenAddress string `json:"token_address"`
	IsActive     bool   `json:"is_active"`
}

type GetPositionsByTokenRow struct {
	ID           int64              `json:"id"`
	WalletID     int64              `json:"wallet_id"`
	TokenAddress string             `json:"token_address"`
	TokenSymbol  pgtype.Text        `json:"token_symbol"`
	Amount       pgtype.Numeric     `json:"amount"`
	EntryPrice   pgtype.Numeric     `json:"entry_price"`
	CurrentPrice pgtype.Numeric     `json:"current_price"`
	PnlUsd       pgtype.Numeric     `json:"pnl_usd"`
	OpenedAt     pgtype.Timestamptz `json:"opened_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsActive     bool               `json:"is_active"`
	UserID       int64              `json:"user_id"`
	WalletName   string             `json:"wallet_name"`
}

func (q *Queries) GetPositionsByToken(ctx context.Context, arg GetPositionsByTokenParams) ([]GetPositionsByTokenRow, error) {
	rows, err := q.db.Query(ctx, getPositionsByToken, arg.TokenAddress, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPositionsByTokenRow{}
	for rows.Next() {
		var i GetPositionsByTokenRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TokenAddress,
			&i.TokenSymbol,
			&i.Amount,
			&i.EntryPrice,
			&i.CurrentPrice,
			&i.PnlUsd,
			&i.OpenedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.UserID,
			&i.WalletName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPositionsForPriceUpdate = `-- name: GetPositionsForPriceUpdate :many
SELECT id, wallet_id, token_address, current_price
FROM token_positions
WHERE is_active = true AND updated_at < NOW() - INTERVAL '5 minutes'
ORDER BY updated_at ASC
LIMIT $1
`

type GetPositionsForPriceUpdateRow struct {
	ID           int64          `json:"id"`
	WalletID     int64          `json:"wallet_id"`
	TokenAddress string         `json:"token_address"`
	CurrentPrice pgtype.Numeric `json:"current_price"`
}

func (q *Queries) GetPositionsForPriceUpdate(ctx context.Context, limit int32) ([]GetPositionsForPriceUpdateRow, error) {
	rows, err := q.db.Query(ctx, getPositionsForPriceUpdate, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPositionsForPriceUpdateRow{}
	for rows.Next() {
		var i GetPositionsForPriceUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TokenAddress,
			&i.CurrentPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPositionsPnLSummary = `-- name: GetPositionsPnLSummary :one
SELECT 
    COUNT(*) as total_active_positions,
    COALESCE(SUM(pnl_usd), 0) as total_pnl_usd,
    COALESCE(AVG(pnl_usd), 0) as avg_pnl_usd,
    COALESCE(SUM(CASE WHEN pnl_usd > 0 THEN pnl_usd ELSE 0 END), 0) as total_profit_usd,
    COALESCE(SUM(CASE WHEN pnl_usd < 0 THEN pnl_usd ELSE 0 END), 0) as total_loss_usd,
    COUNT(CASE WHEN pnl_usd > 0 THEN 1 END) as winning_positions,
    COUNT(CASE WHEN pnl_usd < 0 THEN 1 END) as losing_positions
FROM token_positions
WHERE wallet_id = $1 AND is_active = true
`

type GetPositionsPnLSummaryRow struct {
	TotalActivePositions int64       `json:"total_active_positions"`
	TotalPnlUsd          interface{} `json:"total_pnl_usd"`
	AvgPnlUsd            interface{} `json:"avg_pnl_usd"`
	TotalProfitUsd       interface{} `json:"total_profit_usd"`
	TotalLossUsd         interface{} `json:"total_loss_usd"`
	WinningPositions     int64       `json:"winning_positions"`
	LosingPositions      int64       `json:"losing_positions"`
}

func (q *Queries) GetPositionsPnLSummary(ctx context.Context, walletID int64) (GetPositionsPnLSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPositionsPnLSummary, walletID)
	var i GetPositionsPnLSummaryRow
	err := row.Scan(
		&i.TotalActivePositions,
		&i.TotalPnlUsd,
		&i.AvgPnlUsd,
		&i.TotalProfitUsd,
		&i.TotalLossUsd,
		&i.WinningPositions,
		&i.LosingPositions,
	)
	return i, err
}

const getTokenPosition = `-- name: GetTokenPosition :one
SELECT id, wallet_id, token_address, token_symbol, amount, entry_price, current_price, pnl_usd, opened_at, updated_at, is_active
FROM token_positions
WHERE id = $1
`

func (q *Queries) GetTokenPosition(ctx context.Context, id int64) (TokenPositions, error) {
	row := q.db.QueryRow(ctx, getTokenPosition, id)
	var i TokenPositions
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TokenAddress,
		&i.TokenSymbol,
		&i.Amount,
		&i.EntryPrice,
		&i.CurrentPrice,
		&i.PnlUsd,
		&i.OpenedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getTopPnLPositions = `-- name: GetTopPnLPositions :many
SELECT id, wallet_id, token_address, token_symbol, amount, entry_price, current_price, pnl_usd, opened_at, updated_at, is_active
FROM token_positions
WHERE wallet_id = $1 AND is_active = true AND pnl_usd IS NOT NULL
ORDER BY pnl_usd DESC
LIMIT $2
`

type GetTopPnLPositionsParams struct {
	WalletID int64 `json:"wallet_id"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) GetTopPnLPositions(ctx context.Context, arg GetTopPnLPositionsParams) ([]TokenPositions, error) {
	rows, err := q.db.Query(ctx, getTopPnLPositions, arg.WalletID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenPositions{}
	for rows.Next() {
		var i TokenPositions
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TokenAddress,
			&i.TokenSymbol,
			&i.Amount,
			&i.EntryPrice,
			&i.CurrentPrice,
			&i.PnlUsd,
			&i.OpenedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTokenPositionAmount = `-- name: UpdateTokenPositionAmount :exec
UPDATE token_positions
SET amount = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTokenPositionAmountParams struct {
	ID     int64          `json:"id"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) UpdateTokenPositionAmount(ctx context.Context, arg UpdateTokenPositionAmountParams) error {
	_, err := q.db.Exec(ctx, updateTokenPositionAmount, arg.ID, arg.Amount)
	return err
}

const updateTokenPositionPnL = `-- name: UpdateTokenPositionPnL :exec
UPDATE token_positions
SET current_price = $2, pnl_usd = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateTokenPositionPnLParams struct {
	ID           int64          `json:"id"`
	CurrentPrice pgtype.Numeric `json:"current_price"`
	PnlUsd       pgtype.Numeric `json:"pnl_usd"`
}

func (q *Queries) UpdateTokenPositionPnL(ctx context.Context, arg UpdateTokenPositionPnLParams) error {
	_, err := q.db.Exec(ctx, updateTokenPositionPnL, arg.ID, arg.CurrentPrice, arg.PnlUsd)
	return err
}

const updateTokenPositionPrice = `-- name: UpdateTokenPositionPrice :exec
UPDATE token_positions
SET current_price = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTokenPositionPriceParams struct {
	ID           int64          `json:"id"`
	CurrentPrice pgtype.Numeric `json:"current_price"`
}

func (q *Queries) UpdateTokenPositionPrice(ctx context.Context, arg UpdateTokenPositionPriceParams) error {
	_, err := q.db.Exec(ctx, updateTokenPositionPrice, arg.ID, arg.CurrentPrice)
	return err
}
