// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_balances.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredBalances = `-- name: DeleteExpiredBalances :exec
DELETE FROM user_balances
WHERE cache_valid_until <= NOW() - INTERVAL '1 hour'
`

func (q *Queries) DeleteExpiredBalances(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredBalances)
	return err
}

const deleteUserBalance = `-- name: DeleteUserBalance :exec
DELETE FROM user_balances
WHERE wallet_id = $1
`

func (q *Queries) DeleteUserBalance(ctx context.Context, walletID int64) error {
	_, err := q.db.Exec(ctx, deleteUserBalance, walletID)
	return err
}

const extendBalanceCache = `-- name: ExtendBalanceCache :exec
UPDATE user_balances
SET cache_valid_until = NOW() + INTERVAL '10 minutes'
WHERE wallet_id = $1
`

func (q *Queries) ExtendBalanceCache(ctx context.Context, walletID int64) error {
	_, err := q.db.Exec(ctx, extendBalanceCache, walletID)
	return err
}

const getAllUserBalances = `-- name: GetAllUserBalances :many
SELECT ub.id, ub.wallet_id, ub.sol_balance, ub.last_updated, ub.cache_valid_until,
       w.user_id, w.name as wallet_name
FROM user_balances ub
JOIN wallet w ON ub.wallet_id = w.id
WHERE w.user_id = $1
ORDER BY ub.last_updated DESC
`

type GetAllUserBalancesRow struct {
	ID              int64              `json:"id"`
	WalletID        int64              `json:"wallet_id"`
	SolBalance      pgtype.Numeric     `json:"sol_balance"`
	LastUpdated     pgtype.Timestamptz `json:"last_updated"`
	CacheValidUntil pgtype.Timestamptz `json:"cache_valid_until"`
	UserID          int64              `json:"user_id"`
	WalletName      string             `json:"wallet_name"`
}

func (q *Queries) GetAllUserBalances(ctx context.Context, userID int64) ([]GetAllUserBalancesRow, error) {
	rows, err := q.db.Query(ctx, getAllUserBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUserBalancesRow{}
	for rows.Next() {
		var i GetAllUserBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.SolBalance,
			&i.LastUpdated,
			&i.CacheValidUntil,
			&i.UserID,
			&i.WalletName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalanceStats = `-- name: GetBalanceStats :one
SELECT 
    COUNT(*) as total_cached_balances,
    COUNT(CASE WHEN cache_valid_until > NOW() THEN 1 END) as valid_cached_balances,
    SUM(sol_balance) as total_sol_across_all_users
FROM user_balances
`

type GetBalanceStatsRow struct {
	TotalCachedBalances    int64 `json:"total_cached_balances"`
	ValidCachedBalances    int64 `json:"valid_cached_balances"`
	TotalSolAcrossAllUsers int64 `json:"total_sol_across_all_users"`
}

func (q *Queries) GetBalanceStats(ctx context.Context) (GetBalanceStatsRow, error) {
	row := q.db.QueryRow(ctx, getBalanceStats)
	var i GetBalanceStatsRow
	err := row.Scan(&i.TotalCachedBalances, &i.ValidCachedBalances, &i.TotalSolAcrossAllUsers)
	return i, err
}

const getExpiredBalances = `-- name: GetExpiredBalances :many
SELECT id, wallet_id, sol_balance, last_updated, cache_valid_until
FROM user_balances
WHERE cache_valid_until <= NOW()
ORDER BY cache_valid_until ASC
LIMIT $1
`

func (q *Queries) GetExpiredBalances(ctx context.Context, limit int32) ([]UserBalances, error) {
	rows, err := q.db.Query(ctx, getExpiredBalances, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBalances{}
	for rows.Next() {
		var i UserBalances
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.SolBalance,
			&i.LastUpdated,
			&i.CacheValidUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBalance = `-- name: GetUserBalance :one
SELECT id, wallet_id, sol_balance, last_updated, cache_valid_until
FROM user_balances
WHERE wallet_id = $1
`

func (q *Queries) GetUserBalance(ctx context.Context, walletID int64) (UserBalances, error) {
	row := q.db.QueryRow(ctx, getUserBalance, walletID)
	var i UserBalances
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.SolBalance,
		&i.LastUpdated,
		&i.CacheValidUntil,
	)
	return i, err
}

const getValidUserBalance = `-- name: GetValidUserBalance :one
SELECT id, wallet_id, sol_balance, last_updated, cache_valid_until
FROM user_balances
WHERE wallet_id = $1 AND cache_valid_until > NOW()
`

func (q *Queries) GetValidUserBalance(ctx context.Context, walletID int64) (UserBalances, error) {
	row := q.db.QueryRow(ctx, getValidUserBalance, walletID)
	var i UserBalances
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.SolBalance,
		&i.LastUpdated,
		&i.CacheValidUntil,
	)
	return i, err
}

const updateBalanceAmount = `-- name: UpdateBalanceAmount :exec
UPDATE user_balances
SET sol_balance = $2, last_updated = NOW()
WHERE wallet_id = $1
`

type UpdateBalanceAmountParams struct {
	WalletID   int64          `json:"wallet_id"`
	SolBalance pgtype.Numeric `json:"sol_balance"`
}

func (q *Queries) UpdateBalanceAmount(ctx context.Context, arg UpdateBalanceAmountParams) error {
	_, err := q.db.Exec(ctx, updateBalanceAmount, arg.WalletID, arg.SolBalance)
	return err
}

const upsertUserBalance = `-- name: UpsertUserBalance :exec
INSERT INTO user_balances (wallet_id, sol_balance, last_updated, cache_valid_until)
VALUES ($1, $2, NOW(), NOW() + INTERVAL '10 minutes')
ON CONFLICT (wallet_id) 
DO UPDATE SET 
    sol_balance = EXCLUDED.sol_balance,
    last_updated = NOW(),
    cache_valid_until = NOW() + INTERVAL '10 minutes'
`

type UpsertUserBalanceParams struct {
	WalletID   int64          `json:"wallet_id"`
	SolBalance pgtype.Numeric `json:"sol_balance"`
}

func (q *Queries) UpsertUserBalance(ctx context.Context, arg UpsertUserBalanceParams) error {
	_, err := q.db.Exec(ctx, upsertUserBalance, arg.WalletID, arg.SolBalance)
	return err
}
