// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSettings = `-- name: CreateUserSettings :exec
INSERT INTO user_settings (user_id, buy_slippage, sell_slippage, priority_fee, jito_tip, default_sol_amount, 
                          sell_preset_25, sell_preset_50, sell_preset_75, sell_preset_100,
                          buy_preset_1, buy_preset_2, buy_preset_3, buy_preset_4, buy_preset_5, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW(), NOW())
`

type CreateUserSettingsParams struct {
	UserID           int64          `json:"user_id"`
	BuySlippage      pgtype.Numeric `json:"buy_slippage"`
	SellSlippage     pgtype.Numeric `json:"sell_slippage"`
	PriorityFee      int64          `json:"priority_fee"`
	JitoTip          int64          `json:"jito_tip"`
	DefaultSolAmount pgtype.Numeric `json:"default_sol_amount"`
	SellPreset25     pgtype.Numeric `json:"sell_preset_25"`
	SellPreset50     pgtype.Numeric `json:"sell_preset_50"`
	SellPreset75     pgtype.Numeric `json:"sell_preset_75"`
	SellPreset100    pgtype.Numeric `json:"sell_preset_100"`
	BuyPreset1       pgtype.Numeric `json:"buy_preset_1"`
	BuyPreset2       pgtype.Numeric `json:"buy_preset_2"`
	BuyPreset3       pgtype.Numeric `json:"buy_preset_3"`
	BuyPreset4       pgtype.Numeric `json:"buy_preset_4"`
	BuyPreset5       pgtype.Numeric `json:"buy_preset_5"`
}

func (q *Queries) CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) error {
	_, err := q.db.Exec(ctx, createUserSettings,
		arg.UserID,
		arg.BuySlippage,
		arg.SellSlippage,
		arg.PriorityFee,
		arg.JitoTip,
		arg.DefaultSolAmount,
		arg.SellPreset25,
		arg.SellPreset50,
		arg.SellPreset75,
		arg.SellPreset100,
		arg.BuyPreset1,
		arg.BuyPreset2,
		arg.BuyPreset3,
		arg.BuyPreset4,
		arg.BuyPreset5,
	)
	return err
}

const deleteUserSettings = `-- name: DeleteUserSettings :exec
DELETE FROM user_settings
WHERE user_id = $1
`

func (q *Queries) DeleteUserSettings(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserSettings, userID)
	return err
}

const getSettingsWithDefaults = `-- name: GetSettingsWithDefaults :one
SELECT 
    COALESCE(us.buy_slippage, 15.0) as buy_slippage,
    COALESCE(us.sell_slippage, 1.0) as sell_slippage,
    COALESCE(us.priority_fee, 1000) as priority_fee,
    COALESCE(us.jito_tip, 100000) as jito_tip,
    COALESCE(us.default_sol_amount, 0.1) as default_sol_amount,
    COALESCE(us.sell_preset_25, 25.0) as sell_preset_25,
    COALESCE(us.sell_preset_50, 50.0) as sell_preset_50,
    COALESCE(us.sell_preset_75, 75.0) as sell_preset_75,
    COALESCE(us.sell_preset_100, 100.0) as sell_preset_100,
    COALESCE(us.buy_preset_1, 0.01) as buy_preset_1,
    COALESCE(us.buy_preset_2, 0.05) as buy_preset_2,
    COALESCE(us.buy_preset_3, 0.1) as buy_preset_3,
    COALESCE(us.buy_preset_4, 0.5) as buy_preset_4,
    COALESCE(us.buy_preset_5, 1.0) as buy_preset_5
FROM (SELECT $1::bigint as user_id) AS u
LEFT JOIN user_settings us ON us.user_id = u.user_id
`

type GetSettingsWithDefaultsRow struct {
	BuySlippage      pgtype.Numeric `json:"buy_slippage"`
	SellSlippage     pgtype.Numeric `json:"sell_slippage"`
	PriorityFee      int64          `json:"priority_fee"`
	JitoTip          int64          `json:"jito_tip"`
	DefaultSolAmount pgtype.Numeric `json:"default_sol_amount"`
	SellPreset25     pgtype.Numeric `json:"sell_preset_25"`
	SellPreset50     pgtype.Numeric `json:"sell_preset_50"`
	SellPreset75     pgtype.Numeric `json:"sell_preset_75"`
	SellPreset100    pgtype.Numeric `json:"sell_preset_100"`
	BuyPreset1       pgtype.Numeric `json:"buy_preset_1"`
	BuyPreset2       pgtype.Numeric `json:"buy_preset_2"`
	BuyPreset3       pgtype.Numeric `json:"buy_preset_3"`
	BuyPreset4       pgtype.Numeric `json:"buy_preset_4"`
	BuyPreset5       pgtype.Numeric `json:"buy_preset_5"`
}

func (q *Queries) GetSettingsWithDefaults(ctx context.Context, dollar_1 int64) (GetSettingsWithDefaultsRow, error) {
	row := q.db.QueryRow(ctx, getSettingsWithDefaults, dollar_1)
	var i GetSettingsWithDefaultsRow
	err := row.Scan(
		&i.BuySlippage,
		&i.SellSlippage,
		&i.PriorityFee,
		&i.JitoTip,
		&i.DefaultSolAmount,
		&i.SellPreset25,
		&i.SellPreset50,
		&i.SellPreset75,
		&i.SellPreset100,
		&i.BuyPreset1,
		&i.BuyPreset2,
		&i.BuyPreset3,
		&i.BuyPreset4,
		&i.BuyPreset5,
	)
	return i, err
}

const getUserBuyPresets = `-- name: GetUserBuyPresets :one
SELECT user_id, buy_preset_1, buy_preset_2, buy_preset_3, buy_preset_4, buy_preset_5
FROM user_settings
WHERE user_id = $1
`

type GetUserBuyPresetsRow struct {
	UserID     int64          `json:"user_id"`
	BuyPreset1 pgtype.Numeric `json:"buy_preset_1"`
	BuyPreset2 pgtype.Numeric `json:"buy_preset_2"`
	BuyPreset3 pgtype.Numeric `json:"buy_preset_3"`
	BuyPreset4 pgtype.Numeric `json:"buy_preset_4"`
	BuyPreset5 pgtype.Numeric `json:"buy_preset_5"`
}

func (q *Queries) GetUserBuyPresets(ctx context.Context, userID int64) (GetUserBuyPresetsRow, error) {
	row := q.db.QueryRow(ctx, getUserBuyPresets, userID)
	var i GetUserBuyPresetsRow
	err := row.Scan(
		&i.UserID,
		&i.BuyPreset1,
		&i.BuyPreset2,
		&i.BuyPreset3,
		&i.BuyPreset4,
		&i.BuyPreset5,
	)
	return i, err
}

const getUserFeeSettings = `-- name: GetUserFeeSettings :one
SELECT user_id, priority_fee, jito_tip
FROM user_settings
WHERE user_id = $1
`

type GetUserFeeSettingsRow struct {
	UserID      int64 `json:"user_id"`
	PriorityFee int64 `json:"priority_fee"`
	JitoTip     int64 `json:"jito_tip"`
}

func (q *Queries) GetUserFeeSettings(ctx context.Context, userID int64) (GetUserFeeSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUserFeeSettings, userID)
	var i GetUserFeeSettingsRow
	err := row.Scan(&i.UserID, &i.PriorityFee, &i.JitoTip)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, buy_slippage, sell_slippage, priority_fee, jito_tip, default_sol_amount,
       sell_preset_25, sell_preset_50, sell_preset_75, sell_preset_100,
       buy_preset_1, buy_preset_2, buy_preset_3, buy_preset_4, buy_preset_5, created_at, updated_at
FROM user_settings
WHERE user_id = $1
`

type GetUserSettingsRow struct {
	UserID           int64              `json:"user_id"`
	BuySlippage      pgtype.Numeric     `json:"buy_slippage"`
	SellSlippage     pgtype.Numeric     `json:"sell_slippage"`
	PriorityFee      int64              `json:"priority_fee"`
	JitoTip          int64              `json:"jito_tip"`
	DefaultSolAmount pgtype.Numeric     `json:"default_sol_amount"`
	SellPreset25     pgtype.Numeric     `json:"sell_preset_25"`
	SellPreset50     pgtype.Numeric     `json:"sell_preset_50"`
	SellPreset75     pgtype.Numeric     `json:"sell_preset_75"`
	SellPreset100    pgtype.Numeric     `json:"sell_preset_100"`
	BuyPreset1       pgtype.Numeric     `json:"buy_preset_1"`
	BuyPreset2       pgtype.Numeric     `json:"buy_preset_2"`
	BuyPreset3       pgtype.Numeric     `json:"buy_preset_3"`
	BuyPreset4       pgtype.Numeric     `json:"buy_preset_4"`
	BuyPreset5       pgtype.Numeric     `json:"buy_preset_5"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserSettings(ctx context.Context, userID int64) (GetUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i GetUserSettingsRow
	err := row.Scan(
		&i.UserID,
		&i.BuySlippage,
		&i.SellSlippage,
		&i.PriorityFee,
		&i.JitoTip,
		&i.DefaultSolAmount,
		&i.SellPreset25,
		&i.SellPreset50,
		&i.SellPreset75,
		&i.SellPreset100,
		&i.BuyPreset1,
		&i.BuyPreset2,
		&i.BuyPreset3,
		&i.BuyPreset4,
		&i.BuyPreset5,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSlippageSettings = `-- name: GetUserSlippageSettings :one
SELECT user_id, buy_slippage, sell_slippage
FROM user_settings
WHERE user_id = $1
`

type GetUserSlippageSettingsRow struct {
	UserID       int64          `json:"user_id"`
	BuySlippage  pgtype.Numeric `json:"buy_slippage"`
	SellSlippage pgtype.Numeric `json:"sell_slippage"`
}

func (q *Queries) GetUserSlippageSettings(ctx context.Context, userID int64) (GetUserSlippageSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUserSlippageSettings, userID)
	var i GetUserSlippageSettingsRow
	err := row.Scan(&i.UserID, &i.BuySlippage, &i.SellSlippage)
	return i, err
}

const getUserTradingPresets = `-- name: GetUserTradingPresets :one
SELECT user_id, default_sol_amount, sell_preset_25, sell_preset_50, sell_preset_75, sell_preset_100
FROM user_settings
WHERE user_id = $1
`

type GetUserTradingPresetsRow struct {
	UserID           int64          `json:"user_id"`
	DefaultSolAmount pgtype.Numeric `json:"default_sol_amount"`
	SellPreset25     pgtype.Numeric `json:"sell_preset_25"`
	SellPreset50     pgtype.Numeric `json:"sell_preset_50"`
	SellPreset75     pgtype.Numeric `json:"sell_preset_75"`
	SellPreset100    pgtype.Numeric `json:"sell_preset_100"`
}

func (q *Queries) GetUserTradingPresets(ctx context.Context, userID int64) (GetUserTradingPresetsRow, error) {
	row := q.db.QueryRow(ctx, getUserTradingPresets, userID)
	var i GetUserTradingPresetsRow
	err := row.Scan(
		&i.UserID,
		&i.DefaultSolAmount,
		&i.SellPreset25,
		&i.SellPreset50,
		&i.SellPreset75,
		&i.SellPreset100,
	)
	return i, err
}

const updateBuyPresets = `-- name: UpdateBuyPresets :exec
UPDATE user_settings
SET buy_preset_1 = $2, buy_preset_2 = $3, buy_preset_3 = $4, buy_preset_4 = $5, buy_preset_5 = $6, updated_at = NOW()
WHERE user_id = $1
`

type UpdateBuyPresetsParams struct {
	UserID     int64          `json:"user_id"`
	BuyPreset1 pgtype.Numeric `json:"buy_preset_1"`
	BuyPreset2 pgtype.Numeric `json:"buy_preset_2"`
	BuyPreset3 pgtype.Numeric `json:"buy_preset_3"`
	BuyPreset4 pgtype.Numeric `json:"buy_preset_4"`
	BuyPreset5 pgtype.Numeric `json:"buy_preset_5"`
}

func (q *Queries) UpdateBuyPresets(ctx context.Context, arg UpdateBuyPresetsParams) error {
	_, err := q.db.Exec(ctx, updateBuyPresets,
		arg.UserID,
		arg.BuyPreset1,
		arg.BuyPreset2,
		arg.BuyPreset3,
		arg.BuyPreset4,
		arg.BuyPreset5,
	)
	return err
}

const updateDefaultSolAmount = `-- name: UpdateDefaultSolAmount :exec
UPDATE user_settings
SET default_sol_amount = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateDefaultSolAmountParams struct {
	UserID           int64          `json:"user_id"`
	DefaultSolAmount pgtype.Numeric `json:"default_sol_amount"`
}

func (q *Queries) UpdateDefaultSolAmount(ctx context.Context, arg UpdateDefaultSolAmountParams) error {
	_, err := q.db.Exec(ctx, updateDefaultSolAmount, arg.UserID, arg.DefaultSolAmount)
	return err
}

const updateFeeSettings = `-- name: UpdateFeeSettings :exec
UPDATE user_settings
SET priority_fee = $2, jito_tip = $3, updated_at = NOW()
WHERE user_id = $1
`

type UpdateFeeSettingsParams struct {
	UserID      int64 `json:"user_id"`
	PriorityFee int64 `json:"priority_fee"`
	JitoTip     int64 `json:"jito_tip"`
}

func (q *Queries) UpdateFeeSettings(ctx context.Context, arg UpdateFeeSettingsParams) error {
	_, err := q.db.Exec(ctx, updateFeeSettings, arg.UserID, arg.PriorityFee, arg.JitoTip)
	return err
}

const updateJitoTip = `-- name: UpdateJitoTip :exec
UPDATE user_settings
SET jito_tip = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateJitoTipParams struct {
	UserID  int64 `json:"user_id"`
	JitoTip int64 `json:"jito_tip"`
}

func (q *Queries) UpdateJitoTip(ctx context.Context, arg UpdateJitoTipParams) error {
	_, err := q.db.Exec(ctx, updateJitoTip, arg.UserID, arg.JitoTip)
	return err
}

const updatePriorityFee = `-- name: UpdatePriorityFee :exec
UPDATE user_settings
SET priority_fee = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdatePriorityFeeParams struct {
	UserID      int64 `json:"user_id"`
	PriorityFee int64 `json:"priority_fee"`
}

func (q *Queries) UpdatePriorityFee(ctx context.Context, arg UpdatePriorityFeeParams) error {
	_, err := q.db.Exec(ctx, updatePriorityFee, arg.UserID, arg.PriorityFee)
	return err
}

const updateSellPresets = `-- name: UpdateSellPresets :exec
UPDATE user_settings
SET sell_preset_25 = $2, sell_preset_50 = $3, sell_preset_75 = $4, sell_preset_100 = $5, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSellPresetsParams struct {
	UserID        int64          `json:"user_id"`
	SellPreset25  pgtype.Numeric `json:"sell_preset_25"`
	SellPreset50  pgtype.Numeric `json:"sell_preset_50"`
	SellPreset75  pgtype.Numeric `json:"sell_preset_75"`
	SellPreset100 pgtype.Numeric `json:"sell_preset_100"`
}

func (q *Queries) UpdateSellPresets(ctx context.Context, arg UpdateSellPresetsParams) error {
	_, err := q.db.Exec(ctx, updateSellPresets,
		arg.UserID,
		arg.SellPreset25,
		arg.SellPreset50,
		arg.SellPreset75,
		arg.SellPreset100,
	)
	return err
}

const updateSingleBuyPreset1 = `-- name: UpdateSingleBuyPreset1 :exec
UPDATE user_settings
SET buy_preset_1 = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSingleBuyPreset1Params struct {
	UserID     int64          `json:"user_id"`
	BuyPreset1 pgtype.Numeric `json:"buy_preset_1"`
}

func (q *Queries) UpdateSingleBuyPreset1(ctx context.Context, arg UpdateSingleBuyPreset1Params) error {
	_, err := q.db.Exec(ctx, updateSingleBuyPreset1, arg.UserID, arg.BuyPreset1)
	return err
}

const updateSingleBuyPreset2 = `-- name: UpdateSingleBuyPreset2 :exec
UPDATE user_settings
SET buy_preset_2 = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSingleBuyPreset2Params struct {
	UserID     int64          `json:"user_id"`
	BuyPreset2 pgtype.Numeric `json:"buy_preset_2"`
}

func (q *Queries) UpdateSingleBuyPreset2(ctx context.Context, arg UpdateSingleBuyPreset2Params) error {
	_, err := q.db.Exec(ctx, updateSingleBuyPreset2, arg.UserID, arg.BuyPreset2)
	return err
}

const updateSingleBuyPreset3 = `-- name: UpdateSingleBuyPreset3 :exec
UPDATE user_settings
SET buy_preset_3 = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSingleBuyPreset3Params struct {
	UserID     int64          `json:"user_id"`
	BuyPreset3 pgtype.Numeric `json:"buy_preset_3"`
}

func (q *Queries) UpdateSingleBuyPreset3(ctx context.Context, arg UpdateSingleBuyPreset3Params) error {
	_, err := q.db.Exec(ctx, updateSingleBuyPreset3, arg.UserID, arg.BuyPreset3)
	return err
}

const updateSingleBuyPreset4 = `-- name: UpdateSingleBuyPreset4 :exec
UPDATE user_settings
SET buy_preset_4 = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSingleBuyPreset4Params struct {
	UserID     int64          `json:"user_id"`
	BuyPreset4 pgtype.Numeric `json:"buy_preset_4"`
}

func (q *Queries) UpdateSingleBuyPreset4(ctx context.Context, arg UpdateSingleBuyPreset4Params) error {
	_, err := q.db.Exec(ctx, updateSingleBuyPreset4, arg.UserID, arg.BuyPreset4)
	return err
}

const updateSingleBuyPreset5 = `-- name: UpdateSingleBuyPreset5 :exec
UPDATE user_settings
SET buy_preset_5 = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSingleBuyPreset5Params struct {
	UserID     int64          `json:"user_id"`
	BuyPreset5 pgtype.Numeric `json:"buy_preset_5"`
}

func (q *Queries) UpdateSingleBuyPreset5(ctx context.Context, arg UpdateSingleBuyPreset5Params) error {
	_, err := q.db.Exec(ctx, updateSingleBuyPreset5, arg.UserID, arg.BuyPreset5)
	return err
}

const updateSingleSellPreset1 = `-- name: UpdateSingleSellPreset1 :exec
UPDATE user_settings
SET sell_preset_25 = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSingleSellPreset1Params struct {
	UserID       int64          `json:"user_id"`
	SellPreset25 pgtype.Numeric `json:"sell_preset_25"`
}

func (q *Queries) UpdateSingleSellPreset1(ctx context.Context, arg UpdateSingleSellPreset1Params) error {
	_, err := q.db.Exec(ctx, updateSingleSellPreset1, arg.UserID, arg.SellPreset25)
	return err
}

const updateSingleSellPreset2 = `-- name: UpdateSingleSellPreset2 :exec
UPDATE user_settings
SET sell_preset_50 = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSingleSellPreset2Params struct {
	UserID       int64          `json:"user_id"`
	SellPreset50 pgtype.Numeric `json:"sell_preset_50"`
}

func (q *Queries) UpdateSingleSellPreset2(ctx context.Context, arg UpdateSingleSellPreset2Params) error {
	_, err := q.db.Exec(ctx, updateSingleSellPreset2, arg.UserID, arg.SellPreset50)
	return err
}

const updateSingleSellPreset3 = `-- name: UpdateSingleSellPreset3 :exec
UPDATE user_settings
SET sell_preset_75 = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSingleSellPreset3Params struct {
	UserID       int64          `json:"user_id"`
	SellPreset75 pgtype.Numeric `json:"sell_preset_75"`
}

func (q *Queries) UpdateSingleSellPreset3(ctx context.Context, arg UpdateSingleSellPreset3Params) error {
	_, err := q.db.Exec(ctx, updateSingleSellPreset3, arg.UserID, arg.SellPreset75)
	return err
}

const updateSingleSellPreset4 = `-- name: UpdateSingleSellPreset4 :exec
UPDATE user_settings
SET sell_preset_100 = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSingleSellPreset4Params struct {
	UserID        int64          `json:"user_id"`
	SellPreset100 pgtype.Numeric `json:"sell_preset_100"`
}

func (q *Queries) UpdateSingleSellPreset4(ctx context.Context, arg UpdateSingleSellPreset4Params) error {
	_, err := q.db.Exec(ctx, updateSingleSellPreset4, arg.UserID, arg.SellPreset100)
	return err
}

const updateSlippageSettings = `-- name: UpdateSlippageSettings :exec
UPDATE user_settings
SET buy_slippage = $2, sell_slippage = $3, updated_at = NOW()
WHERE user_id = $1
`

type UpdateSlippageSettingsParams struct {
	UserID       int64          `json:"user_id"`
	BuySlippage  pgtype.Numeric `json:"buy_slippage"`
	SellSlippage pgtype.Numeric `json:"sell_slippage"`
}

func (q *Queries) UpdateSlippageSettings(ctx context.Context, arg UpdateSlippageSettingsParams) error {
	_, err := q.db.Exec(ctx, updateSlippageSettings, arg.UserID, arg.BuySlippage, arg.SellSlippage)
	return err
}

const upsertUserSettings = `-- name: UpsertUserSettings :exec
INSERT INTO user_settings (user_id, buy_slippage, sell_slippage, priority_fee, jito_tip, default_sol_amount, 
                          sell_preset_25, sell_preset_50, sell_preset_75, sell_preset_100,
                          buy_preset_1, buy_preset_2, buy_preset_3, buy_preset_4, buy_preset_5, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW(), NOW())
ON CONFLICT (user_id)
DO UPDATE SET
    buy_slippage = EXCLUDED.buy_slippage,
    sell_slippage = EXCLUDED.sell_slippage,
    priority_fee = EXCLUDED.priority_fee,
    jito_tip = EXCLUDED.jito_tip,
    default_sol_amount = EXCLUDED.default_sol_amount,
    sell_preset_25 = EXCLUDED.sell_preset_25,
    sell_preset_50 = EXCLUDED.sell_preset_50,
    sell_preset_75 = EXCLUDED.sell_preset_75,
    sell_preset_100 = EXCLUDED.sell_preset_100,
    buy_preset_1 = EXCLUDED.buy_preset_1,
    buy_preset_2 = EXCLUDED.buy_preset_2,
    buy_preset_3 = EXCLUDED.buy_preset_3,
    buy_preset_4 = EXCLUDED.buy_preset_4,
    buy_preset_5 = EXCLUDED.buy_preset_5,
    updated_at = NOW()
`

type UpsertUserSettingsParams struct {
	UserID           int64          `json:"user_id"`
	BuySlippage      pgtype.Numeric `json:"buy_slippage"`
	SellSlippage     pgtype.Numeric `json:"sell_slippage"`
	PriorityFee      int64          `json:"priority_fee"`
	JitoTip          int64          `json:"jito_tip"`
	DefaultSolAmount pgtype.Numeric `json:"default_sol_amount"`
	SellPreset25     pgtype.Numeric `json:"sell_preset_25"`
	SellPreset50     pgtype.Numeric `json:"sell_preset_50"`
	SellPreset75     pgtype.Numeric `json:"sell_preset_75"`
	SellPreset100    pgtype.Numeric `json:"sell_preset_100"`
	BuyPreset1       pgtype.Numeric `json:"buy_preset_1"`
	BuyPreset2       pgtype.Numeric `json:"buy_preset_2"`
	BuyPreset3       pgtype.Numeric `json:"buy_preset_3"`
	BuyPreset4       pgtype.Numeric `json:"buy_preset_4"`
	BuyPreset5       pgtype.Numeric `json:"buy_preset_5"`
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertUserSettings,
		arg.UserID,
		arg.BuySlippage,
		arg.SellSlippage,
		arg.PriorityFee,
		arg.JitoTip,
		arg.DefaultSolAmount,
		arg.SellPreset25,
		arg.SellPreset50,
		arg.SellPreset75,
		arg.SellPreset100,
		arg.BuyPreset1,
		arg.BuyPreset2,
		arg.BuyPreset3,
		arg.BuyPreset4,
		arg.BuyPreset5,
	)
	return err
}
