// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wallet.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultWallets = `-- name: ClearDefaultWallets :exec
UPDATE wallet
SET is_default = false
WHERE user_id = $1
`

func (q *Queries) ClearDefaultWallets(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearDefaultWallets, userID)
	return err
}

const countUserWallets = `-- name: CountUserWallets :one
SELECT COUNT(*)
FROM wallet
WHERE user_id = $1
`

func (q *Queries) CountUserWallets(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserWallets, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallet
WHERE id = $1 AND user_id = $2
`

type DeleteWalletParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteWallet(ctx context.Context, arg DeleteWalletParams) error {
	_, err := q.db.Exec(ctx, deleteWallet, arg.ID, arg.UserID)
	return err
}

const findDefaultWalletByUserID = `-- name: FindDefaultWalletByUserID :one
SELECT id, user_id, name, public_key, private_key, mnemonic, created_at, is_default
FROM wallet
WHERE user_id = $1 AND is_default = true
`

type FindDefaultWalletByUserIDRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	Mnemonic   pgtype.Text        `json:"mnemonic"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	IsDefault  bool               `json:"is_default"`
}

func (q *Queries) FindDefaultWalletByUserID(ctx context.Context, userID int64) (FindDefaultWalletByUserIDRow, error) {
	row := q.db.QueryRow(ctx, findDefaultWalletByUserID, userID)
	var i FindDefaultWalletByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.PrivateKey,
		&i.Mnemonic,
		&i.CreatedAt,
		&i.IsDefault,
	)
	return i, err
}

const findDefaultWalletWithEncryption = `-- name: FindDefaultWalletWithEncryption :one
SELECT id, user_id, name, public_key, encrypted_private_key, private_key_nonce,
       encrypted_mnemonic, mnemonic_nonce, encryption_version, encrypted_at,
       created_at, is_default
FROM wallet
WHERE user_id = $1 AND is_default = true
`

type FindDefaultWalletWithEncryptionRow struct {
	ID                  int64              `json:"id"`
	UserID              int64              `json:"user_id"`
	Name                string             `json:"name"`
	PublicKey           string             `json:"public_key"`
	EncryptedPrivateKey []byte             `json:"encrypted_private_key"`
	PrivateKeyNonce     []byte             `json:"private_key_nonce"`
	EncryptedMnemonic   []byte             `json:"encrypted_mnemonic"`
	MnemonicNonce       []byte             `json:"mnemonic_nonce"`
	EncryptionVersion   int32              `json:"encryption_version"`
	EncryptedAt         pgtype.Timestamptz `json:"encrypted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	IsDefault           bool               `json:"is_default"`
}

func (q *Queries) FindDefaultWalletWithEncryption(ctx context.Context, userID int64) (FindDefaultWalletWithEncryptionRow, error) {
	row := q.db.QueryRow(ctx, findDefaultWalletWithEncryption, userID)
	var i FindDefaultWalletWithEncryptionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.EncryptedPrivateKey,
		&i.PrivateKeyNonce,
		&i.EncryptedMnemonic,
		&i.MnemonicNonce,
		&i.EncryptionVersion,
		&i.EncryptedAt,
		&i.CreatedAt,
		&i.IsDefault,
	)
	return i, err
}

const findUnencryptedWallets = `-- name: FindUnencryptedWallets :many
SELECT id, user_id, name, public_key, private_key, mnemonic, created_at, is_default
FROM wallet
WHERE encrypted_private_key IS NULL OR private_key_nonce IS NULL
ORDER BY created_at ASC
`

type FindUnencryptedWalletsRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	Mnemonic   pgtype.Text        `json:"mnemonic"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	IsDefault  bool               `json:"is_default"`
}

func (q *Queries) FindUnencryptedWallets(ctx context.Context) ([]FindUnencryptedWalletsRow, error) {
	rows, err := q.db.Query(ctx, findUnencryptedWallets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindUnencryptedWalletsRow{}
	for rows.Next() {
		var i FindUnencryptedWalletsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PublicKey,
			&i.PrivateKey,
			&i.Mnemonic,
			&i.CreatedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findWalletByID = `-- name: FindWalletByID :one
SELECT id, user_id, name, public_key, private_key, mnemonic, created_at, is_default
FROM wallet
WHERE id = $1
`

type FindWalletByIDRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	Mnemonic   pgtype.Text        `json:"mnemonic"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	IsDefault  bool               `json:"is_default"`
}

func (q *Queries) FindWalletByID(ctx context.Context, id int64) (FindWalletByIDRow, error) {
	row := q.db.QueryRow(ctx, findWalletByID, id)
	var i FindWalletByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.PrivateKey,
		&i.Mnemonic,
		&i.CreatedAt,
		&i.IsDefault,
	)
	return i, err
}

const findWalletByName = `-- name: FindWalletByName :one
SELECT id, user_id, name, public_key, private_key, mnemonic, created_at, is_default
FROM wallet
WHERE user_id = $1 AND name = $2
`

type FindWalletByNameParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

type FindWalletByNameRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	Mnemonic   pgtype.Text        `json:"mnemonic"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	IsDefault  bool               `json:"is_default"`
}

func (q *Queries) FindWalletByName(ctx context.Context, arg FindWalletByNameParams) (FindWalletByNameRow, error) {
	row := q.db.QueryRow(ctx, findWalletByName, arg.UserID, arg.Name)
	var i FindWalletByNameRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.PrivateKey,
		&i.Mnemonic,
		&i.CreatedAt,
		&i.IsDefault,
	)
	return i, err
}

const findWalletWithEncryption = `-- name: FindWalletWithEncryption :one
SELECT id, user_id, name, public_key, encrypted_private_key, private_key_nonce,
       encrypted_mnemonic, mnemonic_nonce, encryption_version, encrypted_at,
       created_at, is_default
FROM wallet
WHERE id = $1
`

type FindWalletWithEncryptionRow struct {
	ID                  int64              `json:"id"`
	UserID              int64              `json:"user_id"`
	Name                string             `json:"name"`
	PublicKey           string             `json:"public_key"`
	EncryptedPrivateKey []byte             `json:"encrypted_private_key"`
	PrivateKeyNonce     []byte             `json:"private_key_nonce"`
	EncryptedMnemonic   []byte             `json:"encrypted_mnemonic"`
	MnemonicNonce       []byte             `json:"mnemonic_nonce"`
	EncryptionVersion   int32              `json:"encryption_version"`
	EncryptedAt         pgtype.Timestamptz `json:"encrypted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	IsDefault           bool               `json:"is_default"`
}

func (q *Queries) FindWalletWithEncryption(ctx context.Context, id int64) (FindWalletWithEncryptionRow, error) {
	row := q.db.QueryRow(ctx, findWalletWithEncryption, id)
	var i FindWalletWithEncryptionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.EncryptedPrivateKey,
		&i.PrivateKeyNonce,
		&i.EncryptedMnemonic,
		&i.MnemonicNonce,
		&i.EncryptionVersion,
		&i.EncryptedAt,
		&i.CreatedAt,
		&i.IsDefault,
	)
	return i, err
}

const findWalletsByUserID = `-- name: FindWalletsByUserID :many
SELECT id, user_id, name, public_key, private_key, mnemonic, created_at, is_default
FROM wallet
WHERE user_id = $1
ORDER BY created_at DESC
`

type FindWalletsByUserIDRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	Mnemonic   pgtype.Text        `json:"mnemonic"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	IsDefault  bool               `json:"is_default"`
}

func (q *Queries) FindWalletsByUserID(ctx context.Context, userID int64) ([]FindWalletsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, findWalletsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindWalletsByUserIDRow{}
	for rows.Next() {
		var i FindWalletsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PublicKey,
			&i.PrivateKey,
			&i.Mnemonic,
			&i.CreatedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findWalletsWithEncryptionByUserID = `-- name: FindWalletsWithEncryptionByUserID :many
SELECT id, user_id, name, public_key, encrypted_private_key, private_key_nonce,
       encrypted_mnemonic, mnemonic_nonce, encryption_version, encrypted_at,
       created_at, is_default
FROM wallet
WHERE user_id = $1
ORDER BY created_at DESC
`

type FindWalletsWithEncryptionByUserIDRow struct {
	ID                  int64              `json:"id"`
	UserID              int64              `json:"user_id"`
	Name                string             `json:"name"`
	PublicKey           string             `json:"public_key"`
	EncryptedPrivateKey []byte             `json:"encrypted_private_key"`
	PrivateKeyNonce     []byte             `json:"private_key_nonce"`
	EncryptedMnemonic   []byte             `json:"encrypted_mnemonic"`
	MnemonicNonce       []byte             `json:"mnemonic_nonce"`
	EncryptionVersion   int32              `json:"encryption_version"`
	EncryptedAt         pgtype.Timestamptz `json:"encrypted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	IsDefault           bool               `json:"is_default"`
}

func (q *Queries) FindWalletsWithEncryptionByUserID(ctx context.Context, userID int64) ([]FindWalletsWithEncryptionByUserIDRow, error) {
	rows, err := q.db.Query(ctx, findWalletsWithEncryptionByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindWalletsWithEncryptionByUserIDRow{}
	for rows.Next() {
		var i FindWalletsWithEncryptionByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PublicKey,
			&i.EncryptedPrivateKey,
			&i.PrivateKeyNonce,
			&i.EncryptedMnemonic,
			&i.MnemonicNonce,
			&i.EncryptionVersion,
			&i.EncryptedAt,
			&i.CreatedAt,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isWalletEncrypted = `-- name: IsWalletEncrypted :one
SELECT 
    (encrypted_private_key IS NOT NULL AND private_key_nonce IS NOT NULL) as is_encrypted,
    encryption_version
FROM wallet
WHERE id = $1
`

type IsWalletEncryptedRow struct {
	IsEncrypted       pgtype.Bool `json:"is_encrypted"`
	EncryptionVersion int32       `json:"encryption_version"`
}

func (q *Queries) IsWalletEncrypted(ctx context.Context, id int64) (IsWalletEncryptedRow, error) {
	row := q.db.QueryRow(ctx, isWalletEncrypted, id)
	var i IsWalletEncryptedRow
	err := row.Scan(&i.IsEncrypted, &i.EncryptionVersion)
	return i, err
}

const migrateWalletToEncryption = `-- name: MigrateWalletToEncryption :exec
UPDATE wallet
SET encrypted_private_key = $2, private_key_nonce = $3,
    encrypted_mnemonic = $4, mnemonic_nonce = $5,
    encryption_version = $6, encrypted_at = $7,
    private_key = '', mnemonic = ''
WHERE id = $1
`

type MigrateWalletToEncryptionParams struct {
	ID                  int64              `json:"id"`
	EncryptedPrivateKey []byte             `json:"encrypted_private_key"`
	PrivateKeyNonce     []byte             `json:"private_key_nonce"`
	EncryptedMnemonic   []byte             `json:"encrypted_mnemonic"`
	MnemonicNonce       []byte             `json:"mnemonic_nonce"`
	EncryptionVersion   int32              `json:"encryption_version"`
	EncryptedAt         pgtype.Timestamptz `json:"encrypted_at"`
}

func (q *Queries) MigrateWalletToEncryption(ctx context.Context, arg MigrateWalletToEncryptionParams) error {
	_, err := q.db.Exec(ctx, migrateWalletToEncryption,
		arg.ID,
		arg.EncryptedPrivateKey,
		arg.PrivateKeyNonce,
		arg.EncryptedMnemonic,
		arg.MnemonicNonce,
		arg.EncryptionVersion,
		arg.EncryptedAt,
	)
	return err
}

const saveEncryptedWallet = `-- name: SaveEncryptedWallet :exec

INSERT INTO wallet (user_id, name, public_key, encrypted_private_key, private_key_nonce, 
                   encrypted_mnemonic, mnemonic_nonce, encryption_version, encrypted_at, 
                   created_at, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type SaveEncryptedWalletParams struct {
	UserID              int64              `json:"user_id"`
	Name                string             `json:"name"`
	PublicKey           string             `json:"public_key"`
	EncryptedPrivateKey []byte             `json:"encrypted_private_key"`
	PrivateKeyNonce     []byte             `json:"private_key_nonce"`
	EncryptedMnemonic   []byte             `json:"encrypted_mnemonic"`
	MnemonicNonce       []byte             `json:"mnemonic_nonce"`
	EncryptionVersion   int32              `json:"encryption_version"`
	EncryptedAt         pgtype.Timestamptz `json:"encrypted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	IsDefault           bool               `json:"is_default"`
}

// NEW ENCRYPTION-RELATED QUERIES
func (q *Queries) SaveEncryptedWallet(ctx context.Context, arg SaveEncryptedWalletParams) error {
	_, err := q.db.Exec(ctx, saveEncryptedWallet,
		arg.UserID,
		arg.Name,
		arg.PublicKey,
		arg.EncryptedPrivateKey,
		arg.PrivateKeyNonce,
		arg.EncryptedMnemonic,
		arg.MnemonicNonce,
		arg.EncryptionVersion,
		arg.EncryptedAt,
		arg.CreatedAt,
		arg.IsDefault,
	)
	return err
}

const saveWallet = `-- name: SaveWallet :exec
INSERT INTO wallet (user_id, name, public_key, private_key, mnemonic, created_at, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SaveWalletParams struct {
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	PublicKey  string             `json:"public_key"`
	PrivateKey string             `json:"private_key"`
	Mnemonic   pgtype.Text        `json:"mnemonic"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	IsDefault  bool               `json:"is_default"`
}

func (q *Queries) SaveWallet(ctx context.Context, arg SaveWalletParams) error {
	_, err := q.db.Exec(ctx, saveWallet,
		arg.UserID,
		arg.Name,
		arg.PublicKey,
		arg.PrivateKey,
		arg.Mnemonic,
		arg.CreatedAt,
		arg.IsDefault,
	)
	return err
}

const setWalletAsDefault = `-- name: SetWalletAsDefault :exec
UPDATE wallet
SET is_default = CASE
    WHEN id = $2 THEN true
    ELSE false
END
WHERE user_id = $1
`

type SetWalletAsDefaultParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) SetWalletAsDefault(ctx context.Context, arg SetWalletAsDefaultParams) error {
	_, err := q.db.Exec(ctx, setWalletAsDefault, arg.UserID, arg.ID)
	return err
}

const setWalletDefault = `-- name: SetWalletDefault :exec
UPDATE wallet
SET is_default = true
WHERE id = $1 AND user_id = $2
`

type SetWalletDefaultParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) SetWalletDefault(ctx context.Context, arg SetWalletDefaultParams) error {
	_, err := q.db.Exec(ctx, setWalletDefault, arg.ID, arg.UserID)
	return err
}

const updateWallet = `-- name: UpdateWallet :exec
UPDATE wallet
SET name = $2, public_key = $3, private_key = $4, mnemonic = $5, is_default = $6
WHERE id = $1
`

type UpdateWalletParams struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	PublicKey  string      `json:"public_key"`
	PrivateKey string      `json:"private_key"`
	Mnemonic   pgtype.Text `json:"mnemonic"`
	IsDefault  bool        `json:"is_default"`
}

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) error {
	_, err := q.db.Exec(ctx, updateWallet,
		arg.ID,
		arg.Name,
		arg.PublicKey,
		arg.PrivateKey,
		arg.Mnemonic,
		arg.IsDefault,
	)
	return err
}

const updateWalletEncryption = `-- name: UpdateWalletEncryption :exec
UPDATE wallet
SET encrypted_private_key = $2, private_key_nonce = $3,
    encrypted_mnemonic = $4, mnemonic_nonce = $5,
    encryption_version = $6, encrypted_at = $7
WHERE id = $1
`

type UpdateWalletEncryptionParams struct {
	ID                  int64              `json:"id"`
	EncryptedPrivateKey []byte             `json:"encrypted_private_key"`
	PrivateKeyNonce     []byte             `json:"private_key_nonce"`
	EncryptedMnemonic   []byte             `json:"encrypted_mnemonic"`
	MnemonicNonce       []byte             `json:"mnemonic_nonce"`
	EncryptionVersion   int32              `json:"encryption_version"`
	EncryptedAt         pgtype.Timestamptz `json:"encrypted_at"`
}

func (q *Queries) UpdateWalletEncryption(ctx context.Context, arg UpdateWalletEncryptionParams) error {
	_, err := q.db.Exec(ctx, updateWalletEncryption,
		arg.ID,
		arg.EncryptedPrivateKey,
		arg.PrivateKeyNonce,
		arg.EncryptedMnemonic,
		arg.MnemonicNonce,
		arg.EncryptionVersion,
		arg.EncryptedAt,
	)
	return err
}
